#!/usr/bin/expect
#   ./ssh.exp password 10.0.0.1 id
set pass [lrange $argv 0 0]
set server [lrange $argv 1 1]
set name [lrange $argv 2 2]

spawn ssh -t $name@$server "bash"
match_max 100000
expect "*?assword*"
send -- "$pass\r"
send -- "\r"
interact
